baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "JOEL'S SITE"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"

    [Params.Tree]
    use = true
    files = [
        ["HOME", "/works/home.md"],
        ["PROJECTS", "/works/projects.md"],
        ["BLOG", "/works/blog.md"],
        ["ABOUT", "/works/about.md"]
    ]
